[package]
name = "voronwe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.9"
chrono = "0.4.23"
locale_config = "0.3.0"
pure-rust-locales = "0.5.6"
